// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuoSGHuUGBILd2wS-F0LOrtu7d3hIHyrY',
    appId: '1:885360017859:web:cafb3a3ca1589344fcfd76',
    messagingSenderId: '885360017859',
    projectId: 'flutter-firebasepractice',
    authDomain: 'flutter-firebasepractice.firebaseapp.com',
    storageBucket: 'flutter-firebasepractice.appspot.com',
    measurementId: 'G-TC9Z23T4GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi3yDaE0xtZBHvOUMLSCWN9I_5JISx0AU',
    appId: '1:885360017859:android:f2379a7f3be8a2dffcfd76',
    messagingSenderId: '885360017859',
    projectId: 'flutter-firebasepractice',
    storageBucket: 'flutter-firebasepractice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC25rFfBio6G4LbGfcWps9YyUiCqYVQAXA',
    appId: '1:885360017859:ios:f410bf3316f452f9fcfd76',
    messagingSenderId: '885360017859',
    projectId: 'flutter-firebasepractice',
    storageBucket: 'flutter-firebasepractice.appspot.com',
    iosClientId: '885360017859-jma8ttj66fcu42mtkodmbl5d7l4n8lrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.class13firebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC25rFfBio6G4LbGfcWps9YyUiCqYVQAXA',
    appId: '1:885360017859:ios:f410bf3316f452f9fcfd76',
    messagingSenderId: '885360017859',
    projectId: 'flutter-firebasepractice',
    storageBucket: 'flutter-firebasepractice.appspot.com',
    iosClientId: '885360017859-jma8ttj66fcu42mtkodmbl5d7l4n8lrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.class13firebaseauth',
  );
}
